version: '3.8'

services:
  app:
    build: .
    ports:
      - '3333:3333'
    volumes:
      - .:/app
    environment:
      DB_CONNECTION: pg
      DB_HOST: bntest-postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: secret
      DB_DATABASE: bntech
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: bntest-postgres
    environment:
      POSTGRES_DB: bntech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
